<?php

return [
    'default_country' => 'BD',
    'default_currency' => 'BDT',
    'activation_refresh_hours' => (int) env('LICENSE_REFRESH_HOURS', 12),
    'timeout_seconds' => (int) env('LICENSE_TIMEOUT_SECONDS', 10),
    'dummy_mode' => env('LICENSE_DUMMY_MODE', true),
    'dummy_keys' => [
        'IP2-BD-BASIC-TEST-2026' => [
            'plan' => 'basic',
            'licensed_email' => 'basic@test.inventorypro.bd',
        ],
        'IP2-BD-ADVANCE-TEST-2026' => [
            'plan' => 'advance',
            'licensed_email' => 'advance@test.inventorypro.bd',
        ],
        'IP2-BD-PREMIUM-TEST-2026' => [
            'plan' => 'premium',
            'licensed_email' => 'premium@test.inventorypro.bd',
        ],
    ],
    'plans' => [
        'basic' => [
            'label' => 'Basic',
            'price_bdt' => 999,
            'price_label' => 'BDT 999/month',
            'rank' => 1,
        ],
        'advance' => [
            'label' => 'Advance',
            'price_bdt' => 2499,
            'price_label' => 'BDT 2,499/month',
            'rank' => 2,
        ],
        'premium' => [
            'label' => 'Premium',
            'price_bdt' => 4999,
            'price_label' => 'BDT 4,999/month',
            'rank' => 3,
        ],
    ],
    'features' => [
        'customers' => 'basic',
        'suppliers' => 'basic',
        'categories' => 'basic',
        'subcategories' => 'basic',
        'products' => 'basic',
        'attributes' => 'basic',
        'orders' => 'basic',
        'purchases' => 'basic',
        'transactions' => 'basic',
        'banks' => 'basic',
        'order_invoices' => 'advance',
        'order_payments' => 'advance',
        'supplier_payments' => 'advance',
        'coupons' => 'advance',
        'stock_ledger' => 'advance',
        'staff_management' => 'advance',
        'salary_management' => 'advance',
        'advance_salary_management' => 'advance',
        'role_management' => 'advance',
        'branches' => 'premium',
        'branch_switching' => 'premium',
        'stock_transfers' => 'premium',
        'refunds' => 'premium',
        'fulfillment' => 'premium',
    ],
    'feature_labels' => [
        'customers' => 'Customer management',
        'suppliers' => 'Supplier management',
        'categories' => 'Categories',
        'subcategories' => 'Subcategories',
        'products' => 'Products',
        'attributes' => 'Attributes',
        'orders' => 'Sales and orders',
        'purchases' => 'Purchases',
        'transactions' => 'Transactions',
        'banks' => 'Bank accounts',
        'order_invoices' => 'Invoice printing',
        'order_payments' => 'Customer due collection',
        'supplier_payments' => 'Supplier due payments',
        'coupons' => 'Coupons and discounts',
        'stock_ledger' => 'Stock ledger',
        'staff_management' => 'Employee management',
        'salary_management' => 'Salary management',
        'advance_salary_management' => 'Advance salary management',
        'role_management' => 'Roles and permissions',
        'branches' => 'Branch management',
        'branch_switching' => 'Branch switching',
        'stock_transfers' => 'Stock transfers',
        'refunds' => 'Refund workflow',
        'fulfillment' => 'Fulfillment workflow',
    ],
];
